debug: true
spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.220.147.181:33306/gaia_order
        username: gaiadev
        password: shuhai0987

      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.220.147.181:33306/gaia_order
        username: gaiadev
        password: shuhai0987

    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 172.22.227.95:9300

management:
  health:
    db:
      enabled: false